services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - todo-network

  todo-service:
    build: ./todo-service
    container_name: todo-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - todo-network
    depends_on:
      - user-service

networks:
  todo-network:
    driver: bridge
